name: Deploy Shopify Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest

      - name: Set up Shopify credentials
        run: echo "SHOPIFY_PASSWORD=${{ secrets.SHOPIFY_PASSWORD }}" >> $GITHUB_ENV

      - name: Push theme to Shopify
        run: shopify theme push --store https://j7kuar-13.myshopify.com --password ${{ secrets.SHOPIFY_PASSWORD }}
